name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: anaconda-client-env
        channels: conda-forge,bioconda,defaults
        channel-priority: flexible
        use-mamba: true
    - name: Conda info
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
    - name: Install Miniprot and BLAST
      run: |
        mamba install -y blast miniprot
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Cache Mamba
      uses: actions/cache@v2
      with:
        path: ${{ env.CONDA }}
        key: ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
      env:
        CACHE_NUMBER: 0
      id: cache
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip hatch
    - name: Lint with ruff, black and mypy
      run: |
        hatch run lint:all
    - name: Test with pytest and report test coverage
      run: |
        hatch run cov
