name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Download BLAST+
      run: |
        curl -SLk https://ftp.ncbi.nih.gov/blast/executables/blast+/2.14.0/ncbi-blast-2.14.0+-x64-linux.tar.gz | tar -xvzf -
        ncbi-blast-2.14.0+/bin/blastx -version
      if: steps.cacheblast.outputs.cache-hit != 'true'
    - name: Cache BLAST+
      uses: actions/cache@v2
      with:
          path: ncbi-blast-2.14.0+
          key: ${{ runner.os }}-blast-${{ env.CACHE_NUMBER }}
      env:
          CACHE_NUMBER: 0
      id: cacheblast
    - name: Add BLAST+ to PATH
      run: |
        mkdir -p ${HOME}/.local/bin/
        ln -s $(pwd)/ncbi-blast-2.14.0+/bin/* ${HOME}/.local/bin/
    - name: Download Miniprot
      run: |
        curl -SLk https://github.com/lh3/miniprot/releases/download/v0.11/miniprot-0.11_x64-linux.tar.bz2 | tar -xvjf -
        miniprot-0.11_x64-linux/miniprot --version
      if: steps.cacheminiprot.outputs.cache-hit != 'true'
    - name: Cache Miniprot
      uses: actions/cache@v2
      with:
          path: miniprot-0.11_x64-linux
          key: ${{ runner.os }}-miniprot-${{ env.CACHE_NUMBER }}
      env:
          CACHE_NUMBER: 0
      id: cacheminiprot
    - name: Add Miniprot to PATH
      run: |
        mkdir -p ${HOME}/.local/bin/
        ln -s $(pwd)/miniprot-0.11_x64-linux/miniprot ${HOME}/.local/bin/
#    - name: Setup Mambaforge
#      uses: conda-incubator/setup-miniconda@v2
#      with:
#        python-version: ${{ matrix.python-version }}
#        mamba-version: "*"
#        activate-environment: test
#        channels: conda-forge,bioconda,defaults
#        channel-priority: flexible
#        use-only-tar-bz2: true
#    - name: Conda info
#      run: |
#        conda info
#        conda list
#        conda config --show-sources
#        conda config --show
#    - name: Install Miniprot and BLAST
#      run: |
#        mamba install -y blast miniprot
#      if: steps.cache.outputs.cache-hit != 'true'
    - name: Show Python version
      run: python --version
    - name: Show env
      run: env
#    - name: Cache Mamba
#      uses: actions/cache@v2
#      with:
#        path: ~/conda_pkgs_dir
#        key: ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
#      env:
#        CACHE_NUMBER: 0
#      id: cache
    - name: Show BLAST version
      run: blastx -version
    - name: Show Miniprot version
      run: miniprot --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip hatch
    - name: Lint with ruff, black and mypy
      run: |
        hatch run lint:all
    - name: Test with pytest and report test coverage
      run: |
        hatch run cov
